---
  - name: Download adduser libfontconfig
	apt: 
	  pkg:
	  - adduser
	  - libfontconfig
  - name: Download grafana 
	apt:
	  deb: https://dl.grafana.com/oss/release/grafana_7.2.0_amd64.deb   
  - name: Start grafana
	systemd:
	  state: started
	  name: grafana-server
	  daemon_reload: yes
	  enabled: yes